### ISSUE TITLE
Map canvas not refreshing after the result is added to the canvas. 

### ISSUE THREAD

**Issue by Anafi** [OpenDigitalWorks/Rcl-topology-cleaner#23]
For example if you select lines from the cleaned network the selection does not appear in the canvas unless you zoom in or out.

**Comment by Anafi** [comment]
I tried refreshing map canvas after  the layers get added but this did not solve the issue.

**Comment by jorgegil** [comment]
When adding and modifying layers you need to do certain things, namely setting the layer's extent using vlayer.updateExtent(). But here that might not not the problem.

On the other hand you always load the memory layer. If the output type is not memory, you should in fact be loading the real output layer created by the user.

**Comment by jorgegil** [comment]
I wonder if the memory layer gets "lost" or "confused" once the separate cleaning thread is closed? Because it's an object created there and returned to the main module.

**Comment by Anafi** [comment]
It is not always a memory layer it can be memory/shp/postgis. Only the errors layer is always a memory layer

**Comment by Anafi** [comment]
I tried the following and none of them worked. I am just thinking if there is sth wrong with the self.iface property. 

1.  ```self.iface.mapCanvas().refresh()```
2.  ```for layer in self.iface.mapCanvas().layers():
                   layer.triggerRepaint()```
3.  ```self.iface.mapCanvas().refreshAllLayers()```

**Comment by jorgegil** [comment]
I noticed that you are passing iface to the thread class and were originally calling that version instead of the original one given to the plugin. I changed that but no change (the object is the same anyway). the iface on the thread class is not really used or necessary, maybe can be removed.

But I don't think it's that, otherwise it would not load the layer at all. It's more likely to be something with the registry or the CRS of the new layer.

**Comment by jorgegil** [comment]
I've checked the various layers properties and all looks ok on paper. But picking up on my second comment, the layer is an object created in the thread, then passed to the main plugin, then the thread is killed. It must destroy something related to that layer.

We should try loading from file instead of adding the layer object to the canvas. Or some other trick...

**Comment by jorgegil** [comment]
Ok, I can confirm that this is the problem. The layer objects are created in the thread, then passed, then the thread killed. So they hang in the registry, but something is lost.
I made a change returning the results and creating the layers in the main module. The Cleaned layer works as expected and features can be selected.

**Comment by Anafi** [comment]
I was thinking that changing the data type of what the finished signal emits might help. Changing the signal to emit three QObjects did not solve the issue.

**Comment by jorgegil** [comment]
Moving the layers outside the thread worked.
